# BIENVENU ! MODIFIER ICI LES PARAMETRES DE VOTRE PLATEFORME KATALOG
# --------------------------------------------------------------------------------------------------------------------------------------------------
#
# Konsilion - Licence juridique Creative Commons CC-BY-NC
# --------------------------------------------------------------------------------------------------------------------------------------------------



# NAVIGATION
# --------------------------------------------------------------------------------------------------------------------------------------------------

nav:

    - Accueil: pages/accueil.md
    
    - Recherche & D√©veloppement:
        
        - Projets: katalog/projets/home.md

        - T√¢ches: katalog/taches/home.md
        
        - Ressources: katalog/ressources/home.md

        - Ing√©nierie collaborative:

            - De quoi parlons nous ?: pages/presentation.md

            - Katalog: pages/katalog.md
            
    - √Ä propos: pages/informations.md



# SITE INFORMATIONS 
# --------------------------------------------------------------------------------------------------------------------------------------------------

site_name: Konsilion - Low-technologie
site_author: Nicolas Br√©mond
site_description: D√©velopper, proposer et promouvoir la Low-technologie.


# repo_url: https://github.com/konsilion/katalog-template/
# edit_uri: edit/master/docs/

# LANGUE, COULEURS et LOGO
#
# [Liste des couleurs](https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#primary-color)
# --------------------------------------------------------------------------------------------------------------------------------------------------

theme:
    language: fr
    palette:
        primary: blue grey
        accent: green
        scheme: default
    logo: https://github.com/Konsilion/katalog-template/blob/master/docs/kloud/img/logo.png?raw=true
    favicon: https://konsilion.fr/wp/wp-content/uploads/2022/03/Logo_Konsilion_1.png
    name: material
    features:
      - navigation.indexes
      - navigation.tracking
      - navigation.top



extra:
  generator: false

# MENTIONS 
# --------------------------------------------------------------------------------------------------------------------------------------------------

copyright: Une plateforme open-source cod√© avec ü§ç par Konsilion - Licence juridique Creative Commons CC-BY-NC 4.0 <br> Un grand merci √† <u><a href="https://www.multi.coop/">multi</a></u> et <u><a href="https://squidfunk.github.io/mkdocs-material/">mkdocs-material</a></u> pour le support technique 







# AUTRES PARAMETRES - Ne pas modifier
# --------------------------------------------------------------------------------------------------------------------------------------------------
plugins:
  - search

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
      
extra_css:
  - https://konsilion.github.io/katalog-setup/css/konsilion-datami.css
  - https://konsilion.github.io/katalog-setup/css/konsilion-mkdocs.css
  - https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css
  
extra_js:
  - https://kit.fontawesome.com/f9666d4f53.js
